-- ========================= CREATE Poses TABLE =============================
CREATE TABLE
    poses (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        image BIGINT NOT NULL REFERENCES images (id) ON DELETE SET NULL,
        created_at TIMESTAMP
        WITH
            TIME ZONE NULL DEFAULT NOW ()
    ) TABLESPACE pg_default;

ALTER TABLE poses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON poses AS PERMISSIVE FOR ALL TO public USING (true);