-- ========================= CREATE OrderStatus TYPE =============================
CREATE TYPE orderStatus AS ENUM (
    'WAITING',
    'IN_PROCESS',
    'COMPLETED',
    'CANCELLED',
    'FAILED'
);

-- ========================= CREATE Orders TABLE =============================
CREATE TABLE
    orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        user_id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
        model BIGINT NOT NULL REFERENCES models (id) ON DELETE SET NULL,
        status orderStatus NULL DEFAULT 'WAITING',
        created_at TIMESTAMP
        WITH
            TIME ZONE NULL DEFAULT NOW ()
    ) TABLESPACE pg_default;

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON orders AS PERMISSIVE FOR ALL TO public USING (true);