-- ========================= CREATE Models TABLE =============================
CREATE TABLE
    models (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        tensor_file_url VARCHAR(2048) NULL,
        created_at TIMESTAMP
        WITH
            TIME ZONE NULL DEFAULT NOW ()
    ) TABLESPACE pg_default;

ALTER TABLE models ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON models AS PERMISSIVE FOR ALL TO public USING (true);

-- ========================= CREATE Models Images BETWEEN TABLE =============================
CREATE TABLE
    models_images (
        model_id BIGINT NOT NULL REFERENCES models (id) ON DELETE CASCADE,
        image_id BIGINT NOT NULL REFERENCES images (id) ON DELETE CASCADE,
        PRIMARY KEY (model_id, image_id)
    ) TABLESPACE pg_default;

ALTER TABLE models_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON models_images AS PERMISSIVE FOR ALL TO public USING (true);