-- ========================= CREATE Key Type TYPE =============================
CREATE TYPE keyType AS ENUM ('PUBLIC', 'PRIVATE');

-- ========================= CREATE Key Status TYPE =============================
CREATE TYPE keyStatus AS ENUM ('ACTIVE', 'EXPIRED', 'DELETED');

-- ========================= CREATE Keys TABLE =============================
CREATE TABLE
    keys (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
        name VARCHAR(120) NOT NULL,
        user_id UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
        type keyType NOT NULL,
        status keyStatus NULL DEFAULT 'ACTIVE',
        exp TIMESTAMP NOT NULL,
        key TEXT NOT NULL,
        created_at TIMESTAMP
        WITH
            TIME ZONE NULL DEFAULT NOW ()
    ) TABLESPACE pg_default;

ALTER TABLE keys ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON keys AS PERMISSIVE FOR ALL TO public USING (true);